### ISSUE TITLE
[question] - 리드미 내용 질문

### ISSUE THREAD

**Issue by C17AN** [bullgom/MyCPP20PracticeProjects#1]
안녕하세요, 궁금한 점이 있어 찾아왔습니다.
리드미에 '포킹 당해도 좋은' 이라고 써있는데, 포킹 당하면 불리하지 않나요..?

![image](https://user-images.githubusercontent.com/26535030/109420962-9e62a200-7a18-11eb-8faa-55b9f79d73cf.png)

**Comment by bullgom** [comment]
좋은 지적 감사합니다. 불리합니다. 워모그의 갑옷을 장착하도록 하겠습니다.
